autoreconf

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1157,6 +1157,10 @@ XQUARTZ_TRUE
 XQUARTZ_FALSE
 DGA_TRUE
 DGA_FALSE
+XF86MISC_TRUE
+XF86MISC_FALSE
+XF86VIDMODE_TRUE
+XF86VIDMODE_FALSE
 MFB_TRUE
 MFB_FALSE
 CFB_TRUE
@@ -5272,7 +5276,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5275 "configure"' > conftest.$ac_ext
+  echo '#line 5279 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8304,11 +8308,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8307: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8311: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8311: \$? = $ac_status" >&5
+   echo "$as_me:8315: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8594,11 +8598,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8597: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8601: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8601: \$? = $ac_status" >&5
+   echo "$as_me:8605: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8698,11 +8702,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8701: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8705: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8705: \$? = $ac_status" >&5
+   echo "$as_me:8709: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11060,7 +11064,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11063 "configure"
+#line 11067 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11160,7 +11164,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11163 "configure"
+#line 11167 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13580,11 +13584,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13583: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13587: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13587: \$? = $ac_status" >&5
+   echo "$as_me:13591: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13684,11 +13688,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13687: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13691: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13691: \$? = $ac_status" >&5
+   echo "$as_me:13695: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15261,11 +15265,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15264: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15268: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15268: \$? = $ac_status" >&5
+   echo "$as_me:15272: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15365,11 +15369,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15368: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15372: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15372: \$? = $ac_status" >&5
+   echo "$as_me:15376: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17565,11 +17569,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17568: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17572: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17572: \$? = $ac_status" >&5
+   echo "$as_me:17576: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17855,11 +17859,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17858: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17862: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17862: \$? = $ac_status" >&5
+   echo "$as_me:17866: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17959,11 +17963,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17962: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17966: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17966: \$? = $ac_status" >&5
+   echo "$as_me:17970: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -34110,6 +34114,22 @@ else
   DGA_FALSE=
 fi
 
+ if test "x$XF86MISC" = xyes; then
+  XF86MISC_TRUE=
+  XF86MISC_FALSE='#'
+else
+  XF86MISC_TRUE='#'
+  XF86MISC_FALSE=
+fi
+
+ if test "x$XF86VIDMODE" = xyes; then
+  XF86VIDMODE_TRUE=
+  XF86VIDMODE_FALSE='#'
+else
+  XF86VIDMODE_TRUE='#'
+  XF86VIDMODE_FALSE=
+fi
+
 
 test "x$MFB" = xauto && MFB="$XORG"
 test "x$CFB" = xauto && CFB="$XORG"
@@ -37486,6 +37506,20 @@ echo "$as_me: error: conditional \"DGA\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${XF86MISC_TRUE}" && test -z "${XF86MISC_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"XF86MISC\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"XF86MISC\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${XF86VIDMODE_TRUE}" && test -z "${XF86VIDMODE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"XF86VIDMODE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"XF86VIDMODE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${MFB_TRUE}" && test -z "${MFB_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"MFB\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -38979,6 +39013,10 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+XF86MISC_TRUE!$XF86MISC_TRUE$ac_delim
+XF86MISC_FALSE!$XF86MISC_FALSE$ac_delim
+XF86VIDMODE_TRUE!$XF86VIDMODE_TRUE$ac_delim
+XF86VIDMODE_FALSE!$XF86VIDMODE_FALSE$ac_delim
 MFB_TRUE!$MFB_TRUE$ac_delim
 MFB_FALSE!$MFB_FALSE$ac_delim
 CFB_TRUE!$CFB_TRUE$ac_delim
@@ -39072,10 +39110,6 @@ XORGCONFIG_DEP_CFLAGS!$XORGCONFIG_DEP_CFLAGS$ac_delim
 XORGCONFIG_DEP_LIBS!$XORGCONFIG_DEP_LIBS$ac_delim
 XORGCFG_DEP_CFLAGS!$XORGCFG_DEP_CFLAGS$ac_delim
 XORGCFG_DEP_LIBS!$XORGCFG_DEP_LIBS$ac_delim
-APPDEFAULTDIR!$APPDEFAULTDIR$ac_delim
-BUILD_XORGCFG_TRUE!$BUILD_XORGCFG_TRUE$ac_delim
-BUILD_XORGCFG_FALSE!$BUILD_XORGCFG_FALSE$ac_delim
-USE_CURSES_TRUE!$USE_CURSES_TRUE$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -39117,6 +39151,10 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+APPDEFAULTDIR!$APPDEFAULTDIR$ac_delim
+BUILD_XORGCFG_TRUE!$BUILD_XORGCFG_TRUE$ac_delim
+BUILD_XORGCFG_FALSE!$BUILD_XORGCFG_FALSE$ac_delim
+USE_CURSES_TRUE!$USE_CURSES_TRUE$ac_delim
 USE_CURSES_FALSE!$USE_CURSES_FALSE$ac_delim
 BUILD_KBD_MODE_TRUE!$BUILD_KBD_MODE_TRUE$ac_delim
 BUILD_KBD_MODE_FALSE!$BUILD_KBD_MODE_FALSE$ac_delim
@@ -39146,7 +39184,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 27; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 31; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
