Autoreconf

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -922,6 +922,8 @@ KDRIVE_HW_TRUE
 KDRIVE_HW_FALSE
 INSTALL_SETUID_TRUE
 INSTALL_SETUID_FALSE
+SECURE_RPC_TRUE
+SECURE_RPC_FALSE
 INT10_VM86_TRUE
 INT10_VM86_FALSE
 INT10_X86EMU_TRUE
@@ -5276,7 +5278,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5279 "configure"' > conftest.$ac_ext
+  echo '#line 5281 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8308,11 +8310,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8311: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8313: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8315: \$? = $ac_status" >&5
+   echo "$as_me:8317: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8598,11 +8600,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8601: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8603: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8605: \$? = $ac_status" >&5
+   echo "$as_me:8607: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8702,11 +8704,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8705: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8707: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8709: \$? = $ac_status" >&5
+   echo "$as_me:8711: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11064,7 +11066,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11067 "configure"
+#line 11069 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11164,7 +11166,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11167 "configure"
+#line 11169 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13584,11 +13586,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13587: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13589: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13591: \$? = $ac_status" >&5
+   echo "$as_me:13593: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13688,11 +13690,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13691: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13693: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13695: \$? = $ac_status" >&5
+   echo "$as_me:13697: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15265,11 +15267,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15268: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15270: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15272: \$? = $ac_status" >&5
+   echo "$as_me:15274: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15369,11 +15371,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15372: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15374: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15376: \$? = $ac_status" >&5
+   echo "$as_me:15378: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17569,11 +17571,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17572: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17574: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17576: \$? = $ac_status" >&5
+   echo "$as_me:17578: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17859,11 +17861,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17862: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17864: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17866: \$? = $ac_status" >&5
+   echo "$as_me:17868: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17963,11 +17965,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17966: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17968: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17970: \$? = $ac_status" >&5
+   echo "$as_me:17972: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -27729,6 +27731,14 @@ _ACEOF
  { echo "$as_me:$LINENO: result: $SECURE_RPC" >&5
 echo "${ECHO_T}$SECURE_RPC" >&6; }
 
+ if test "x$SECURE_RPC" = xyes; then
+  SECURE_RPC_TRUE=
+  SECURE_RPC_FALSE='#'
+else
+  SECURE_RPC_TRUE='#'
+  SECURE_RPC_FALSE=
+fi
+
 
  if test "x$INT10" = xvm86; then
   INT10_VM86_TRUE=
@@ -37051,6 +37061,13 @@ echo "$as_me: error: conditional \"INSTALL_SETUID\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${SECURE_RPC_TRUE}" && test -z "${SECURE_RPC_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"SECURE_RPC\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"SECURE_RPC\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${INT10_VM86_TRUE}" && test -z "${INT10_VM86_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"INT10_VM86\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -38655,6 +38672,8 @@ KDRIVE_HW_TRUE!$KDRIVE_HW_TRUE$ac_delim
 KDRIVE_HW_FALSE!$KDRIVE_HW_FALSE$ac_delim
 INSTALL_SETUID_TRUE!$INSTALL_SETUID_TRUE$ac_delim
 INSTALL_SETUID_FALSE!$INSTALL_SETUID_FALSE$ac_delim
+SECURE_RPC_TRUE!$SECURE_RPC_TRUE$ac_delim
+SECURE_RPC_FALSE!$SECURE_RPC_FALSE$ac_delim
 INT10_VM86_TRUE!$INT10_VM86_TRUE$ac_delim
 INT10_VM86_FALSE!$INT10_VM86_FALSE$ac_delim
 INT10_X86EMU_TRUE!$INT10_X86EMU_TRUE$ac_delim
@@ -38694,8 +38713,6 @@ XVMC_FALSE!$XVMC_FALSE$ac_delim
 COMPOSITE_TRUE!$COMPOSITE_TRUE$ac_delim
 COMPOSITE_FALSE!$COMPOSITE_FALSE$ac_delim
 MITSHM_TRUE!$MITSHM_TRUE$ac_delim
-MITSHM_FALSE!$MITSHM_FALSE$ac_delim
-XTRAP_TRUE!$XTRAP_TRUE$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -38737,6 +38754,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+MITSHM_FALSE!$MITSHM_FALSE$ac_delim
+XTRAP_TRUE!$XTRAP_TRUE$ac_delim
 XTRAP_FALSE!$XTRAP_FALSE$ac_delim
 RECORD_TRUE!$RECORD_TRUE$ac_delim
 RECORD_FALSE!$RECORD_FALSE$ac_delim
@@ -38832,8 +38851,6 @@ DMXXMUEXAMPLES_DEP_LIBS!$DMXXMUEXAMPLES_DEP_LIBS$ac_delim
 DMXXIEXAMPLES_DEP_CFLAGS!$DMXXIEXAMPLES_DEP_CFLAGS$ac_delim
 DMXXIEXAMPLES_DEP_LIBS!$DMXXIEXAMPLES_DEP_LIBS$ac_delim
 XTSTEXAMPLES_DEP_CFLAGS!$XTSTEXAMPLES_DEP_CFLAGS$ac_delim
-XTSTEXAMPLES_DEP_LIBS!$XTSTEXAMPLES_DEP_LIBS$ac_delim
-XRESEXAMPLES_DEP_CFLAGS!$XRESEXAMPLES_DEP_CFLAGS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -38875,6 +38892,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+XTSTEXAMPLES_DEP_LIBS!$XTSTEXAMPLES_DEP_LIBS$ac_delim
+XRESEXAMPLES_DEP_CFLAGS!$XRESEXAMPLES_DEP_CFLAGS$ac_delim
 XRESEXAMPLES_DEP_LIBS!$XRESEXAMPLES_DEP_LIBS$ac_delim
 X11EXAMPLES_DEP_CFLAGS!$X11EXAMPLES_DEP_CFLAGS$ac_delim
 X11EXAMPLES_DEP_LIBS!$X11EXAMPLES_DEP_LIBS$ac_delim
@@ -38970,8 +38989,6 @@ BUILD_DARWIN_TRUE!$BUILD_DARWIN_TRUE$ac_delim
 BUILD_DARWIN_FALSE!$BUILD_DARWIN_FALSE$ac_delim
 XQUARTZ_TRUE!$XQUARTZ_TRUE$ac_delim
 XQUARTZ_FALSE!$XQUARTZ_FALSE$ac_delim
-DGA_TRUE!$DGA_TRUE$ac_delim
-DGA_FALSE!$DGA_FALSE$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -39013,6 +39030,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+DGA_TRUE!$DGA_TRUE$ac_delim
+DGA_FALSE!$DGA_FALSE$ac_delim
 XF86MISC_TRUE!$XF86MISC_TRUE$ac_delim
 XF86MISC_FALSE!$XF86MISC_FALSE$ac_delim
 XF86VIDMODE_TRUE!$XF86VIDMODE_TRUE$ac_delim
@@ -39108,8 +39127,6 @@ XKB_COMPILED_DIR!$XKB_COMPILED_DIR$ac_delim
 PROJECTROOT!$PROJECTROOT$ac_delim
 XORGCONFIG_DEP_CFLAGS!$XORGCONFIG_DEP_CFLAGS$ac_delim
 XORGCONFIG_DEP_LIBS!$XORGCONFIG_DEP_LIBS$ac_delim
-XORGCFG_DEP_CFLAGS!$XORGCFG_DEP_CFLAGS$ac_delim
-XORGCFG_DEP_LIBS!$XORGCFG_DEP_LIBS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -39151,6 +39168,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+XORGCFG_DEP_CFLAGS!$XORGCFG_DEP_CFLAGS$ac_delim
+XORGCFG_DEP_LIBS!$XORGCFG_DEP_LIBS$ac_delim
 APPDEFAULTDIR!$APPDEFAULTDIR$ac_delim
 BUILD_XORGCFG_TRUE!$BUILD_XORGCFG_TRUE$ac_delim
 BUILD_XORGCFG_FALSE!$BUILD_XORGCFG_FALSE$ac_delim
@@ -39184,7 +39203,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 31; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 33; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
